package com.stackportal.tenant.dto;

import com.stackportal.tenant.entity.TenantStatus;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

/**
 * Request payload for creating or updating a tenant.
 *
 * <p>{@code databaseName}, {@code databaseUrl}, and {@code databaseUsername}
 * are intentionally omitted — they are auto-generated by
 * {@link com.stackportal.tenant.service.TenantDatabaseProvisioner}.</p>
 *
 * <p>{@code databasePassword} is optional. When blank, the provisioner falls
 * back to the master credentials configured in {@code application.yml}.</p>
 */
public record TenantRequest(

        @NotBlank
        String name,

        @NotBlank
        String code,

        String logo,

        @Email
        String email,

        String website,

        String phone,

        String address,

        String city,

        String country,

        /**
         * Optional password for the tenant database user.
         * If null / blank the master DB password is used instead.
         */
        String databasePassword,

        TenantStatus status
) {
}